services:
  git-deploy-server:
    build: .
    ports:
      - "2222:22"
      - "3000:3000"
    volumes:
      - ./scripts/post-receive:/var/repo/site.git/hooks/post-receive
      - ./www:/var/www/domain.com

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www/build:/usr/share/nginx/html
    ports:
      - "8080:80"

  ngrok:
    image: ngrok/ngrok
    command: http nginx:80
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"            
